### ISSUE TITLE
Support SongPro Format

### ISSUE THREAD

**Issue by spilth** [Desbeers/Chord-Provider#13]
I'd love to see this app support the [SongPro](https://songpro.org) format. I tried making my own ([songpro-editor-swiftui](https://github.com/SongProOrg/songpro-editor-swiftui) but never got around to finishing.

Is there any interest in supporting the SongPro format? If so, I might be inclined to take a stab at it in a fork.

**Comment by Desbeers** [comment]
Personally, I have no interest in any other format than ChordPro, however, SongPro format is not that much different from ChordPro format so I don't mind to add support for it as well. Feel free to make a PR!

**Comment by spilth** [comment]
Alright, I'll see what I can make happen 🤞

**Comment by Desbeers** [comment]
Brian, just curious, why did you create your **SongPro** transcription format? It is very close to **ChordPro** except with a little bit less *HTML* feeling. I see the point.

However, **ChordPro** is a bit of a standard for *plain text transcription*. One of the reasons I wrote **Chord Provider** is that I wanted to have an application that supports the standard instead of inventing a new standard.

There are some great applications for transcription, mainly iOS (I'm a macOS user), however, they all *import* **ChordPro** into their own format. I don't like that.

I try to stay as close a possible to **ChordPro**. I rewrote my chord database as a simple  **ChordPro** {define: ...} JSON file with just the instrument added. On purpose. Chords are chords. In my application I parse it and add whatever I like. It analyse the chords, add MIDI notes, find the components etcetera. The chords are just chords.

**Chord Provider** is not stable and will never be. The only part that is stable is that it is a **ChordPro**  application.

I often rewrite essential parts of the application, it is my hobby project.

I'm sorry, unlike my previous comment, I'm not going to support any other format than **ChordPro**.

You are are more than welcome to contribute and make suggestions; My application is not perfect but for sure beautiful!

The question remains, why another 'plain text' format?

Nick

**Comment by spilth** [comment]
> Why did you create your SongPro transcription format?

The short answer is that I wanted something I personally found easier to parse both with my eyes and with my code.

>I'm sorry, unlike my previous comment, I'm not going to support any other format than ChordPro.

No worries. Thank you for considering it.

**Comment by Desbeers** [comment]
Thanks for your kind reply Brain.

I'm interested in your long answer!

**Comment by spilth** [comment]
The long answer, all my humble opinion:

- ChordPro's structure/syntax seems a bit dated
- SongPro is easier to read and write
- In making my own song book I found I was wrestling with ChordPro and didn't really have control over what it was doing
- I'm a programmer and it's fun to build stuff
- I wanted to make something that looked a bit more like Markdown
- I think at the time I started working on it ChordPro did not have Chord Grids, which was something I wanted (I might be wrong about this)

And to be frank, the format hasn't taken off. SongPro isn't used by many people but it serves my songbook very well.

**Comment by Desbeers** [comment]
Thanks Brian,

I'm thinking about it.... My response might take some time.

I work on a ship and back to sea tomorrow...

Nick
